services:
  db:
    image: postgres:15-alpine
    container_name: hacka_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - hacka_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: hacka_backend
    ports:
      - "8080:8080"
    environment:
      - API_PORT=8080
      - JWT_SECRET=my_secret_key_for_development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=postgres
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - go_mod_cache:/go/pkg/mod
    working_dir: /app
    command: ["go", "run", "main.go"]
    networks:
      - hacka_network
    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: hacka_adminer
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: hydra
    depends_on:
      - db
    networks:
      - hacka_network
    restart: unless-stopped

networks:
  hacka_network:
    driver: bridge

volumes:
  postgres_data:
  go_mod_cache:
