// Code generated by SQLBoiler 4.19.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Activity string
	Benefit  string
	Employee string
	Feedback string
	Resource string
}{
	Activity: "activity",
	Benefit:  "benefit",
	Employee: "employee",
	Feedback: "feedback",
	Resource: "resource",
}
