// Code generated by SQLBoiler 4.19.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Activities", testActivitiesUpsert)

	t.Run("Employees", testEmployeesUpsert)

	t.Run("Feedbacks", testFeedbacksUpsert)

	t.Run("Resources", testResourcesUpsert)
}
