// Code generated by SQLBoiler 4.19.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Resource is an object representing the database table.
type Resource struct {
	ID        string       `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name      null.String  `boil:"name" json:"name,omitempty" toml:"name" yaml:"name,omitempty"`
	Type      null.String  `boil:"type" json:"type,omitempty" toml:"type" yaml:"type,omitempty"`
	Midia     null.String  `boil:"midia" json:"midia,omitempty" toml:"midia" yaml:"midia,omitempty"`
	Average   null.Float64 `boil:"average" json:"average,omitempty" toml:"average" yaml:"average,omitempty"`
	CreatedAt null.Time    `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt null.Time    `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`
	Image     null.String  `boil:"image" json:"image,omitempty" toml:"image" yaml:"image,omitempty"`

	R *resourceR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L resourceL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ResourceColumns = struct {
	ID        string
	Name      string
	Type      string
	Midia     string
	Average   string
	CreatedAt string
	UpdatedAt string
	Image     string
}{
	ID:        "id",
	Name:      "name",
	Type:      "type",
	Midia:     "midia",
	Average:   "average",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	Image:     "image",
}

var ResourceTableColumns = struct {
	ID        string
	Name      string
	Type      string
	Midia     string
	Average   string
	CreatedAt string
	UpdatedAt string
	Image     string
}{
	ID:        "resource.id",
	Name:      "resource.name",
	Type:      "resource.type",
	Midia:     "resource.midia",
	Average:   "resource.average",
	CreatedAt: "resource.created_at",
	UpdatedAt: "resource.updated_at",
	Image:     "resource.image",
}

// Generated where

var ResourceWhere = struct {
	ID        whereHelperstring
	Name      whereHelpernull_String
	Type      whereHelpernull_String
	Midia     whereHelpernull_String
	Average   whereHelpernull_Float64
	CreatedAt whereHelpernull_Time
	UpdatedAt whereHelpernull_Time
	Image     whereHelpernull_String
}{
	ID:        whereHelperstring{field: "\"resource\".\"id\""},
	Name:      whereHelpernull_String{field: "\"resource\".\"name\""},
	Type:      whereHelpernull_String{field: "\"resource\".\"type\""},
	Midia:     whereHelpernull_String{field: "\"resource\".\"midia\""},
	Average:   whereHelpernull_Float64{field: "\"resource\".\"average\""},
	CreatedAt: whereHelpernull_Time{field: "\"resource\".\"created_at\""},
	UpdatedAt: whereHelpernull_Time{field: "\"resource\".\"updated_at\""},
	Image:     whereHelpernull_String{field: "\"resource\".\"image\""},
}

// ResourceRels is where relationship names are stored.
var ResourceRels = struct {
}{}

// resourceR is where relationships are stored.
type resourceR struct {
}

// NewStruct creates a new relationship struct
func (*resourceR) NewStruct() *resourceR {
	return &resourceR{}
}

// resourceL is where Load methods for each relationship are stored.
type resourceL struct{}

var (
	resourceAllColumns            = []string{"id", "name", "type", "midia", "average", "created_at", "updated_at", "image"}
	resourceColumnsWithoutDefault = []string{}
	resourceColumnsWithDefault    = []string{"id", "name", "type", "midia", "average", "created_at", "updated_at", "image"}
	resourcePrimaryKeyColumns     = []string{"id"}
	resourceGeneratedColumns      = []string{}
)

type (
	// ResourceSlice is an alias for a slice of pointers to Resource.
	// This should almost always be used instead of []Resource.
	ResourceSlice []*Resource
	// ResourceHook is the signature for custom Resource hook methods
	ResourceHook func(context.Context, boil.ContextExecutor, *Resource) error

	resourceQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	resourceType                 = reflect.TypeOf(&Resource{})
	resourceMapping              = queries.MakeStructMapping(resourceType)
	resourcePrimaryKeyMapping, _ = queries.BindMapping(resourceType, resourceMapping, resourcePrimaryKeyColumns)
	resourceInsertCacheMut       sync.RWMutex
	resourceInsertCache          = make(map[string]insertCache)
	resourceUpdateCacheMut       sync.RWMutex
	resourceUpdateCache          = make(map[string]updateCache)
	resourceUpsertCacheMut       sync.RWMutex
	resourceUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var resourceAfterSelectMu sync.Mutex
var resourceAfterSelectHooks []ResourceHook

var resourceBeforeInsertMu sync.Mutex
var resourceBeforeInsertHooks []ResourceHook
var resourceAfterInsertMu sync.Mutex
var resourceAfterInsertHooks []ResourceHook

var resourceBeforeUpdateMu sync.Mutex
var resourceBeforeUpdateHooks []ResourceHook
var resourceAfterUpdateMu sync.Mutex
var resourceAfterUpdateHooks []ResourceHook

var resourceBeforeDeleteMu sync.Mutex
var resourceBeforeDeleteHooks []ResourceHook
var resourceAfterDeleteMu sync.Mutex
var resourceAfterDeleteHooks []ResourceHook

var resourceBeforeUpsertMu sync.Mutex
var resourceBeforeUpsertHooks []ResourceHook
var resourceAfterUpsertMu sync.Mutex
var resourceAfterUpsertHooks []ResourceHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Resource) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range resourceAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Resource) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range resourceBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Resource) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range resourceAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Resource) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range resourceBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Resource) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range resourceAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Resource) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range resourceBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Resource) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range resourceAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Resource) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range resourceBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Resource) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range resourceAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddResourceHook registers your hook function for all future operations.
func AddResourceHook(hookPoint boil.HookPoint, resourceHook ResourceHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		resourceAfterSelectMu.Lock()
		resourceAfterSelectHooks = append(resourceAfterSelectHooks, resourceHook)
		resourceAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		resourceBeforeInsertMu.Lock()
		resourceBeforeInsertHooks = append(resourceBeforeInsertHooks, resourceHook)
		resourceBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		resourceAfterInsertMu.Lock()
		resourceAfterInsertHooks = append(resourceAfterInsertHooks, resourceHook)
		resourceAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		resourceBeforeUpdateMu.Lock()
		resourceBeforeUpdateHooks = append(resourceBeforeUpdateHooks, resourceHook)
		resourceBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		resourceAfterUpdateMu.Lock()
		resourceAfterUpdateHooks = append(resourceAfterUpdateHooks, resourceHook)
		resourceAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		resourceBeforeDeleteMu.Lock()
		resourceBeforeDeleteHooks = append(resourceBeforeDeleteHooks, resourceHook)
		resourceBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		resourceAfterDeleteMu.Lock()
		resourceAfterDeleteHooks = append(resourceAfterDeleteHooks, resourceHook)
		resourceAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		resourceBeforeUpsertMu.Lock()
		resourceBeforeUpsertHooks = append(resourceBeforeUpsertHooks, resourceHook)
		resourceBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		resourceAfterUpsertMu.Lock()
		resourceAfterUpsertHooks = append(resourceAfterUpsertHooks, resourceHook)
		resourceAfterUpsertMu.Unlock()
	}
}

// One returns a single resource record from the query.
func (q resourceQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Resource, error) {
	o := &Resource{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for resource")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Resource records from the query.
func (q resourceQuery) All(ctx context.Context, exec boil.ContextExecutor) (ResourceSlice, error) {
	var o []*Resource

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Resource slice")
	}

	if len(resourceAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Resource records in the query.
func (q resourceQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count resource rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q resourceQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if resource exists")
	}

	return count > 0, nil
}

// Resources retrieves all the records using an executor.
func Resources(mods ...qm.QueryMod) resourceQuery {
	mods = append(mods, qm.From("\"resource\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"resource\".*"})
	}

	return resourceQuery{q}
}

// FindResource retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindResource(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*Resource, error) {
	resourceObj := &Resource{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"resource\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, resourceObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from resource")
	}

	if err = resourceObj.doAfterSelectHooks(ctx, exec); err != nil {
		return resourceObj, err
	}

	return resourceObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Resource) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no resource provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(resourceColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	resourceInsertCacheMut.RLock()
	cache, cached := resourceInsertCache[key]
	resourceInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			resourceAllColumns,
			resourceColumnsWithDefault,
			resourceColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(resourceType, resourceMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(resourceType, resourceMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"resource\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"resource\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into resource")
	}

	if !cached {
		resourceInsertCacheMut.Lock()
		resourceInsertCache[key] = cache
		resourceInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Resource.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Resource) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	resourceUpdateCacheMut.RLock()
	cache, cached := resourceUpdateCache[key]
	resourceUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			resourceAllColumns,
			resourcePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update resource, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"resource\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, resourcePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(resourceType, resourceMapping, append(wl, resourcePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update resource row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for resource")
	}

	if !cached {
		resourceUpdateCacheMut.Lock()
		resourceUpdateCache[key] = cache
		resourceUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q resourceQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for resource")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for resource")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ResourceSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), resourcePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"resource\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, resourcePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in resource slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all resource")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Resource) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no resource provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(resourceColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	resourceUpsertCacheMut.RLock()
	cache, cached := resourceUpsertCache[key]
	resourceUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			resourceAllColumns,
			resourceColumnsWithDefault,
			resourceColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			resourceAllColumns,
			resourcePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert resource, could not build update column list")
		}

		ret := strmangle.SetComplement(resourceAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(resourcePrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert resource, could not build conflict column list")
			}

			conflict = make([]string, len(resourcePrimaryKeyColumns))
			copy(conflict, resourcePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"resource\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(resourceType, resourceMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(resourceType, resourceMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert resource")
	}

	if !cached {
		resourceUpsertCacheMut.Lock()
		resourceUpsertCache[key] = cache
		resourceUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Resource record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Resource) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Resource provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), resourcePrimaryKeyMapping)
	sql := "DELETE FROM \"resource\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from resource")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for resource")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q resourceQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no resourceQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from resource")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for resource")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ResourceSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(resourceBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), resourcePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"resource\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, resourcePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from resource slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for resource")
	}

	if len(resourceAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Resource) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindResource(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ResourceSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ResourceSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), resourcePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"resource\".* FROM \"resource\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, resourcePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ResourceSlice")
	}

	*o = slice

	return nil
}

// ResourceExists checks if the Resource row exists.
func ResourceExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"resource\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if resource exists")
	}

	return exists, nil
}

// Exists checks if the Resource row exists.
func (o *Resource) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ResourceExists(ctx, exec, o.ID)
}
